In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('candyhierarchy2017.csv', encoding='latin-1')

In [3]:
df.head()

Internal ID Q1: GOING OUT? Q2: GENDER Q3: AGE Q4: COUNTRY  \
0     90258773            NaN        NaN     NaN         NaN   
1     90272821             No       Male      44        USA    
2     90272829            NaN       Male      49         USA   
3     90272840             No       Male      40          us   
4     90272841             No       Male      23         usa   

  Q5: STATE, PROVINCE, COUNTY, ETC Q6 | 100 Grand Bar  \
0                              NaN                NaN   
1                               NM                MEH   
2                         Virginia                NaN   
3                               or                MEH   
4                         exton pa                JOY   

  Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
0                                                NaN                                       
1                                            DESPAIR                                       
2                                                NaN                                       
3                                            DESPAIR                                       
4                                            DESPAIR                                       

  Q6 | Any full-sized candy bar Q6 | Black Jacks  ... Q8: DESPAIR OTHER  \
0                           NaN              NaN  ...               NaN   
1                           JOY              MEH  ...               NaN   
2                           NaN              NaN  ...               NaN   
3                           JOY              MEH  ...               NaN   
4                           JOY          DESPAIR  ...               NaN   

                                  Q9: OTHER COMMENTS      Q10: DRESS  \
0                                                NaN             NaN   
1  Bottom line is Twix is really the only candy w...  White and gold   
2                                                NaN             NaN   
3                             Raisins can go to hell  White and gold   
4                                                NaN  White and gold   

  Unnamed: 113 Q11: DAY Q12: MEDIA [Daily Dish] Q12: MEDIA [Science]  \
0          NaN      NaN                     NaN                  NaN   
1          NaN   Sunday                     NaN                  1.0   
2          NaN      NaN                     NaN                  NaN   
3          NaN   Sunday                     NaN                  1.0   
4          NaN   Friday                     NaN                  1.0   

  Q12: MEDIA [ESPN] Q12: MEDIA [Yahoo] Click Coordinates (x, y)  
0               NaN                NaN                      NaN  
1               NaN                NaN                 (84, 25)  
2               NaN                NaN                      NaN  
3               NaN                NaN                 (75, 23)  
4               NaN                NaN                 (70, 10)  

[5 rows x 120 columns]

In [4]:
df.shape

(2460, 120)

In [5]:
df.set_index('Internal ID', inplace = True)

In [6]:
df['Unnamed: 113'].value_counts(dropna = False)

NaN                                                                        2451
dress (https://survey.ubc.ca/media/assets/user/14372/storage/dress.png)       9
Name: Unnamed: 113, dtype: int64

In [7]:
## The columns 'Q5: STATE, PROVINCE, COUNTY, ETC', 'Q7: JOY OTHER', 'Q8: DESPAIR OTHER', 'Q9: OTHER COMMENTS', 'Unnamed: 113', and 'Click Coordinates (x, y)' have many missing values and are not useful, hence they will be dropped.
to_drop = ['Q5: STATE, PROVINCE, COUNTY, ETC', 'Q7: JOY OTHER', 'Q8: DESPAIR OTHER', 
           'Q9: OTHER COMMENTS', 'Unnamed: 113', 'Click Coordinates (x, y)']
df.drop(to_drop, inplace = True, axis = 1)

In [8]:
df.dtypes

Q1: GOING OUT?                                                                             object
Q2: GENDER                                                                                 object
Q3: AGE                                                                                    object
Q4: COUNTRY                                                                                object
Q6 | 100 Grand Bar                                                                         object
Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)     object
Q6 | Any full-sized candy bar                                                              object
Q6 | Black Jacks                                                                           object
Q6 | Bonkers (the candy)                                                                   object
Q6 | Bonkers (the board game)                                                              object
Q6 | Bottle Caps    

In [9]:
for col in df:
    if df[col].dtypes == 'float64':
        df[col] = df[col].fillna('0')

In [10]:
df.head()

Q1: GOING OUT? Q2: GENDER Q3: AGE Q4: COUNTRY Q6 | 100 Grand Bar  \
Internal ID                                                                    
90258773               NaN        NaN     NaN         NaN                NaN   
90272821                No       Male      44        USA                 MEH   
90272829               NaN       Male      49         USA                NaN   
90272840                No       Male      40          us                MEH   
90272841                No       Male      23         usa                JOY   

            Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Internal ID                                                                                          
90258773                                                   NaN                                       
90272821                                               DESPAIR                                       
90272829                                                   NaN                                       
90272840                                               DESPAIR                                       
90272841                                               DESPAIR                                       

            Q6 | Any full-sized candy bar Q6 | Black Jacks  \
Internal ID                                                  
90258773                              NaN              NaN   
90272821                              JOY              MEH   
90272829                              NaN              NaN   
90272840                              JOY              MEH   
90272841                              JOY          DESPAIR   

            Q6 | Bonkers (the candy) Q6 | Bonkers (the board game)  ...  \
Internal ID                                                         ...   
90258773                         NaN                           NaN  ...   
90272821                     DESPAIR                       DESPAIR  ...   
90272829                         NaN                           NaN  ...   
90272840                         MEH                       DESPAIR  ...   
90272841                         MEH                       DESPAIR  ...   

            Q6 | Whatchamacallit Bars Q6 | White Bread  \
Internal ID                                              
90258773                          NaN              NaN   
90272821                      DESPAIR          DESPAIR   
90272829                          NaN              NaN   
90272840                          JOY          DESPAIR   
90272841                          JOY          DESPAIR   

            Q6 | Whole Wheat anything Q6 | York Peppermint Patties  \
Internal ID                                                          
90258773                          NaN                          NaN   
90272821                      DESPAIR                      DESPAIR   
90272829                          NaN                          NaN   
90272840                      DESPAIR                      DESPAIR   
90272841                      DESPAIR                          JOY   

                 Q10: DRESS Q11: DAY Q12: MEDIA [Daily Dish]  \
Internal ID                                                    
90258773                NaN      NaN                       0   
90272821     White and gold   Sunday                       0   
90272829                NaN      NaN                       0   
90272840     White and gold   Sunday                       0   
90272841     White and gold   Friday                       0   

            Q12: MEDIA [Science] Q12: MEDIA [ESPN] Q12: MEDIA [Yahoo]  
Internal ID                                                            
90258773                       0                 0                  0  
90272821                       1                 0                  0  
90272829                       0                 0                  0  
90272840                       1                 0                  

In [11]:
candies = df.iloc[:, 6:-10]
candies.describe()

Q6 | Any full-sized candy bar Q6 | Black Jacks  \
count                           1788             1502   
unique                             3                3   
top                              JOY          DESPAIR   
freq                            1559              793   

       Q6 | Bonkers (the candy) Q6 | Bonkers (the board game)  \
count                      1468                          1454   
unique                        3                             3   
top                         MEH                           MEH   
freq                        857                           715   

       Q6 | Bottle Caps Q6 | Box'o'Raisins Q6 | Broken glow stick  \
count              1695               1772                   1754   
unique                3                  3                      3   
top                 MEH            DESPAIR                DESPAIR   
freq                670               1179                   1625   

       Q6 | Butterfinger Q6 | Cadbury Creme Eggs Q6 | Candy Corn  ...  \
count               1778                    1777            1782  ...   
unique                 3                       3               3  ...   
top                  JOY                     JOY         DESPAIR  ...   
freq                1177                     820             743  ...   

       Q6 | Sweetums (a friend to diabetes) Q6 | Take 5 Q6 | Tic Tacs  \
count                                  1458        1543          1746   
unique                                    3           3             3   
top                                 DESPAIR         MEH       DESPAIR   
freq                                    763         613           754   

       Q6 | Those odd marshmallow circus peanut things Q6 | Three Musketeers  \
count                                             1724                  1752   
unique                                               3                     3   
top                                            DESPAIR                   JOY   
freq                                              1252                  1058   

       Q6 | Tolberone something or other Q6 | Trail Mix Q6 | Twix  \
count                               1754           1752      1770   
unique                                 3              3         3   
top                                  JOY        DESPAIR       JOY   
freq                                1320            836      1413   

       Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein  \
count                                                1668                            
unique                                                  3                            
top                                               DESPAIR                            
freq                                                 1146                            

       Q6 | Vicodin  
count          1671  
unique            3  
top         DESPAIR  
freq            723  

[4 rows x 97 columns]

In [12]:
df['Q4: COUNTRY'].unique()

array([nan, 'USA ', 'USA', 'us', 'usa', 'canada', 'Canada', 'Us', 'US',
       'Murica', 'United States', 'uk', 'United Kingdom', 'united states',
       'Usa', 'United States ', 'United staes',
       'United States of America', 'UAE', 'England', 'UK', 'canada ',
       'Mexico', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', '35',
       'france', 'United States of America ', 'U.S.A.', 'finland',
       'unhinged states', 'Canada ', 'united states of america',
       'US of A', 'Unites States', 'The United States', 'North Carolina ',
       'Unied States', 'Netherlands', 'germany', 'Europe', 'Earth', 'U S',
       'u.s.', 'U.K. ', 'Costa Rica', 'The United States of America',
       'unite states', 'U.S.', '46', 'cascadia', 'Australia',
       'insanity lately', 'Greece', 'USA? Hard to tell anymore..',
       "'merica", 'usas', 'Pittsburgh', '45', 'United State', '32',
       'France', 'australia', 'A', 'Can', 'Canae', 'New York',
       'Trumpistan', 'Ireland', 'United Sates', '

In [13]:
df.replace(['murrika', 'Murica', 'A', 'USAA', 'USA ', 'us', 'USA', 'US', 'Us', 'usa', 'united states', 
            'united states of america', 'Usa', 'United States ', 'United staes','United States of America',
            'United states','u.s.a.','USAUSAUSA', 'america', 'United States of America ','U.S.A.', 'unhinged states',
            'united states of america', 'US of A', 'Unites States', 'The United States', 'North Carolina ','Unied States',
            'U S', 'u.s.', 'The United States of America', 'unite states', 'U.S.', 'cascadia', 'USA? Hard to tell anymore..', "'merica", 'usas', 'Pittsburgh', 
            'United State', 'New York', 'Trumpistan', 'United Sates', 'California', 'USa',
            'I pretend to be from Canada, but I am really from the United States.', 'Usa ', 'United Stated',
            'Ahem....Amerca', 'UD', 'New Jersey', 'United ststes', 'America', 'United Statss', 'USA! USA! USA!',
            'Alaska', 'united States ', 'N. America', 'USSA', 'U.S. ', 'u s a', 'United Statea', 'united ststes', 
            'USA USA USA!!!!'], "United States", inplace = True)
df.replace(['Soviet Canuckistan','Soviet canuckistan', 'canada', 'Canada', 'canada ', 'Canada ', 'Can', 'Canae', 'Canada`',
            'CANADA'], "Canada", inplace = True)
df.replace(['United kingdom', 'uk', 'United Kingdom', 'UK', 'U.K. ', 'Uk', 'UK ', 'Scotland ', 'England'], "United Kingdom",
           inplace = True)
df.replace(['finland'], 'Finland', inplace = True)
df.replace(['france', 'France', 'France '], 'France', inplace = True)
df.replace(['The Netherlands', 'Netherlands'], 'Netherlands', inplace = True)
df.replace(['Ireland ', 'Ireland'], 'Ireland', inplace = True)
df.replace(['Uae'], 'United Arab Emirates', inplace = True)
df.replace(['35', 'Europe', 'Earth', '46', 'insanity lately', '45', '32', 'endland', 'Atlantis', 'Narnia', '1', 
            'subscribe to dm4uz3 on youtube',  "I don't know anymore", 'Fear and Loathing'], np.nan, inplace = True)
df['Q4: COUNTRY'] = df['Q4: COUNTRY'].str.title()

In [14]:
df['Q4: COUNTRY'].unique()

array([nan, 'United States', 'Canada', 'United Kingdom', 'Uae', 'Mexico',
       'France', 'Finland', 'Netherlands', 'Germany', 'Costa Rica',
       'Australia', 'Greece', 'Ireland', 'Korea', 'Japan', 'South Africa',
       'Iceland', 'Scotland', 'Denmark', 'Switzerland', 'South Korea',
       'Indonesia', 'Soviet Canuckistan', 'Singapore', 'China', 'Taiwan',
       'Hong Kong', 'Spain', 'Sweden'], dtype=object)

In [15]:
df['Q2: GENDER'].unique()

array([nan, 'Male', 'Female', "I'd rather not say", 'Other'], dtype=object)

In [16]:
df.replace(["I'd rather not say", 'Other'], np.nan, inplace = True)

In [17]:
df['Q3: AGE'].unique()

array([nan, '44', '49', '40', '23', '53', '33', '43', '56', '64', '37',
       '59', '48', '54', '36', '25', '34', '38', '58', '50', '47', '16',
       '52', '63', '65', '41', '27', '31', '61', '42', '62', '29', '39',
       '28', '69', '67', '30', '22', '26', '51', '70', '24', '18', '19',
       'Old enough', '57', '60', '66', '12', 'Many', '55', '72', '?',
       '21', '11', 'no', '9', '68', '20', '6', '10', '71', '90', '13',
       '45-55', '312', '99', '7', 'hahahahaha', '88', '39.4', '74', '102',
       'older than dirt', '17', '15', '8', '75', '5u', 'Enough',
       'See question 2', '24-50', '14', 'Over 50', '100', '76', '1000',
       'sixty-nine', '46 Halloweens.', 'ancient', '77', 'OLD', 'old',
       '73', '70 1/2', 'MY NAME JEFF', '4',
       '59 on the day after Halloween', 'old enough', 'your mom',
       'I can remember when Java was a cool new language', '60+'],
      dtype=object)

In [18]:
# Unexpected missing values will be removed.
df['Q3: AGE'] = df['Q3: AGE'].apply(pd.to_numeric, errors = 'coerce')

In [19]:
df['Q3: AGE'].unique()

array([   nan,   44. ,   49. ,   40. ,   23. ,   53. ,   33. ,   43. ,
         56. ,   64. ,   37. ,   59. ,   48. ,   54. ,   36. ,   25. ,
         34. ,   38. ,   58. ,   50. ,   47. ,   16. ,   52. ,   63. ,
         65. ,   41. ,   27. ,   31. ,   61. ,   42. ,   62. ,   29. ,
         39. ,   28. ,   69. ,   67. ,   30. ,   22. ,   26. ,   51. ,
         70. ,   24. ,   18. ,   19. ,   57. ,   60. ,   66. ,   12. ,
         55. ,   72. ,   21. ,   11. ,    9. ,   68. ,   20. ,    6. ,
         10. ,   71. ,   90. ,   13. ,  312. ,   99. ,    7. ,   88. ,
         39.4,   74. ,  102. ,   17. ,   15. ,    8. ,   75. ,   14. ,
        100. ,   76. , 1000. ,   77. ,   73. ,    4. ])

In [20]:
df.head()

Q1: GOING OUT? Q2: GENDER  Q3: AGE    Q4: COUNTRY  \
Internal ID                                                     
90258773               NaN        NaN      NaN            NaN   
90272821                No       Male     44.0  United States   
90272829               NaN       Male     49.0  United States   
90272840                No       Male     40.0  United States   
90272841                No       Male     23.0  United States   

            Q6 | 100 Grand Bar  \
Internal ID                      
90258773                   NaN   
90272821                   MEH   
90272829                   NaN   
90272840                   MEH   
90272841                   JOY   

            Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)  \
Internal ID                                                                                          
90258773                                                   NaN                                       
90272821                                               DESPAIR                                       
90272829                                                   NaN                                       
90272840                                               DESPAIR                                       
90272841                                               DESPAIR                                       

            Q6 | Any full-sized candy bar Q6 | Black Jacks  \
Internal ID                                                  
90258773                              NaN              NaN   
90272821                              JOY              MEH   
90272829                              NaN              NaN   
90272840                              JOY              MEH   
90272841                              JOY          DESPAIR   

            Q6 | Bonkers (the candy) Q6 | Bonkers (the board game)  ...  \
Internal ID                                                         ...   
90258773                         NaN                           NaN  ...   
90272821                     DESPAIR                       DESPAIR  ...   
90272829                         NaN                           NaN  ...   
90272840                         MEH                       DESPAIR  ...   
90272841                         MEH                       DESPAIR  ...   

            Q6 | Whatchamacallit Bars Q6 | White Bread  \
Internal ID                                              
90258773                          NaN              NaN   
90272821                      DESPAIR          DESPAIR   
90272829                          NaN              NaN   
90272840                          JOY          DESPAIR   
90272841                          JOY          DESPAIR   

            Q6 | Whole Wheat anything Q6 | York Peppermint Patties  \
Internal ID                                                          
90258773                          NaN                          NaN   
90272821                      DESPAIR                      DESPAIR   
90272829                          NaN                          NaN   
90272840                      DESPAIR                      DESPAIR   
90272841                      DESPAIR                          JOY   

                 Q10: DRESS Q11: DAY Q12: MEDIA [Daily Dish]  \
Internal ID                                                    
90258773                NaN      NaN                       0   
90272821     White and gold   Sunday                       0   
90272829                NaN      NaN                       0   
90272840     White and gold   Sunday                       0   
90272841     White and gold   Friday                       0   

            Q12: MEDIA [Science] Q12: MEDIA [ESPN] Q12: MEDIA [Yahoo]  
Internal ID                                                            
90258773                       0                 0                  0  
90272821                       1                 0                  0  
902728